# Generated by Django 2.0 on 2018-01-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20180112_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggedplace',
            old_name='asset',
            new_name='content_object',
        ),
        migrations.RenameField(
            model_name='taggedsubject',
            old_name='asset',
            new_name='content_object',
        ),
    ]
