# Generated by Django 2.0 on 2018-01-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20180112_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typedtag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='data_contact_address',
            new_name='data_contact_address1',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='primary_contact_address',
            new_name='primary_contact_address1',
        ),
        migrations.AddField(
            model_name='asset',
            name='data_contact_address2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address 2'),
        ),
        migrations.AddField(
            model_name='asset',
            name='primary_contact_address2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address 2'),
        ),
    ]
