# Generated by Django 2.0 on 2018-01-17 15:46

import asset.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20180116_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='region',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='asset',
            name='data_contact_state',
            field=models.CharField(choices=[('', 'Choose'), ('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('DC', 'DC'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('PR', 'PR'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('VI', 'VI'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(help_text='Provide an extentive description which provides detailed information about the use, timing, location, and methods of collection or analysis. (Max 10,000 characters)', max_length=10000, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='end_month',
            field=models.CharField(choices=[('', 'Choose'), ('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='end_year',
            field=models.CharField(blank=True, help_text='The last year data were collected, or `Present` if the data are still being collected.', max_length=7, null=True, validators=[asset.validators.validate_end_year], verbose_name='Ending Year'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='isContracted',
            field=models.BooleanField(default=False, help_text='This should be checked for assets in which the storage or maintenance of the asset are performed through a contractual aggreeement with a non-fws entity.', verbose_name='Contracted'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='If this data asset shares a common history, administration, decision context, and/or species + location + platform that requires coordinated planning and management, select the assest that is its parent.', null=True, on_delete=django.db.models.deletion.PROTECT, to='asset.Asset', verbose_name='Parent Asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='primary_contact_state',
            field=models.CharField(choices=[('', 'Choose'), ('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('DC', 'DC'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('PR', 'PR'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('VI', 'VI'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='spatial_scale',
            field=models.CharField(choices=[('', 'Choose Scale'), ('BCR', 'BCR'), ('multi-state', 'multi-State/Province'), ('single state', 'Single State/Province'), ('local', 'local')], help_text='Choose the spatial scale that best represents the largest scale that the data are collected.', max_length=15),
        ),
        migrations.AlterField(
            model_name='asset',
            name='start_month',
            field=models.CharField(blank=True, choices=[('', 'Choose'), ('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='start_year',
            field=models.CharField(blank=True, help_text='The year in which data were first collected', max_length=4, null=True, validators=[asset.validators.validate_start_year], verbose_name='Starting Year'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('', 'Choose status'), ('operational', 'Operational'), ('inactive', 'Inactive'), ('experimental', 'Experimental')], help_text='Selection the value that best represents the current state of the asset. Inactive should be used for assets that have ceased operations or have been discontinued.', max_length=15, verbose_name='Asset Status'),
        ),
    ]
