# Generated by Django 2.0 on 2018-01-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20180119_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='end_month',
            field=models.CharField(blank=True, choices=[('', 'Choose'), ('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3, null=True),
        ),
    ]
