# Generated by Django 2.0 on 2018-01-20 12:44

import asset.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20180119_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='asset',
            name='data_contact_phone_ext',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Extension'),
        ),
        migrations.AddField(
            model_name='asset',
            name='primary_contact_phone_ext',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='data_contact_name',
            field=models.CharField(max_length=50, validators=[asset.validators.validate_name], verbose_name='Data Contact'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='asset.Organization', verbose_name='Primary Organization of Stewardship'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='primary_contact_name',
            field=models.CharField(max_length=50, validators=[asset.validators.validate_name], verbose_name='Primary Contact'),
        ),
    ]
