# Generated by Django 2.0 on 2018-01-23 11:50

import asset.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0009_auto_20180120_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAsset',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='A descriptive name of the asset.', max_length=200, verbose_name='Asset Name')),
                ('status', models.CharField(choices=[('', 'Choose status'), ('operational', 'Operational'), ('inactive', 'Inactive'), ('experimental', 'Experimental')], help_text='Selection the value that best represents the current state of the asset. Inactive should be used for assets that have ceased operations or have been discontinued.', max_length=15, verbose_name='Asset Status')),
                ('isContracted', models.BooleanField(default=False, help_text='This should be checked for assets in which the storage or maintenance of the asset are performed through a contractual aggreeement with a non-fws entity.', verbose_name='Contracted')),
                ('spatial_scale', models.CharField(choices=[('', 'Choose Scale'), ('BCR', 'BCR'), ('multi-state', 'multi-State/Province'), ('single state', 'Single State/Province'), ('local', 'local')], help_text='Choose the spatial scale that best represents the largest scale that the data are collected.', max_length=15)),
                ('start_month', models.CharField(blank=True, choices=[('', 'Choose'), ('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3, null=True)),
                ('end_month', models.CharField(blank=True, choices=[('', 'Choose'), ('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3, null=True)),
                ('description', models.TextField(help_text='Provide an extentive description which provides detailed information about the use, timing, location, and methods of collection or analysis. (Max 10,000 characters)', max_length=10000, verbose_name='Abstract')),
                ('partners', models.CharField(blank=True, help_text='Include all partners as a comma separate list, that have direct involvement in the collection, storage, or maintenance of the asset.', max_length=100, null=True, verbose_name='Partners')),
                ('start_year', models.CharField(blank=True, help_text='The year in which data were first collected', max_length=4, null=True, validators=[asset.validators.validate_start_year], verbose_name='Starting Year')),
                ('end_year', models.CharField(blank=True, help_text='The last year data were collected, or `Present` if the data are still being collected.', max_length=7, null=True, validators=[asset.validators.validate_end_year], verbose_name='Ending Year')),
                ('primary_contact_name', models.CharField(max_length=50, validators=[asset.validators.validate_name], verbose_name='Primary Contact')),
                ('primary_contact_address1', models.CharField(max_length=150, verbose_name='Address')),
                ('primary_contact_address2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address 2')),
                ('primary_contact_city', models.CharField(max_length=50, verbose_name='City')),
                ('primary_contact_state', models.CharField(choices=[('', 'Choose'), ('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('DC', 'DC'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('PR', 'PR'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('VI', 'VI'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], max_length=2, verbose_name='State')),
                ('primary_contact_zip', models.CharField(max_length=5, verbose_name='Zip')),
                ('primary_contact_email', models.EmailField(max_length=254, validators=[asset.validators.validate_primary_email], verbose_name='Email')),
                ('primary_contact_phone', models.CharField(max_length=13, verbose_name='Phone')),
                ('primary_contact_phone_ext', models.CharField(blank=True, max_length=4, null=True, verbose_name='Extension')),
                ('data_contact_name', models.CharField(max_length=50, validators=[asset.validators.validate_name], verbose_name='Data Contact')),
                ('data_contact_address1', models.CharField(max_length=150, verbose_name='Address')),
                ('data_contact_address2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address 2')),
                ('data_contact_city', models.CharField(max_length=50, verbose_name='City')),
                ('data_contact_state', models.CharField(choices=[('', 'Choose'), ('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('DC', 'DC'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('PR', 'PR'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('VI', 'VI'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], max_length=2, verbose_name='State')),
                ('data_contact_zip', models.CharField(max_length=5, verbose_name='Zip')),
                ('data_contact_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('data_contact_phone', models.CharField(max_length=13, verbose_name='Phone')),
                ('data_contact_phone_ext', models.CharField(blank=True, max_length=4, null=True, verbose_name='Extension')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.Organization')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.HistoricalAsset')),
            ],
            options={
                'verbose_name': 'historical asset',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
