# Generated by Django 2.0 on 2018-01-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_historicalasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='data_contact_phone',
            field=models.CharField(max_length=14, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='primary_contact_phone',
            field=models.CharField(max_length=14, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='data_contact_phone',
            field=models.CharField(max_length=14, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='primary_contact_phone',
            field=models.CharField(max_length=14, verbose_name='Phone'),
        ),
    ]
