# Generated by Django 2.0 on 2018-01-23 19:13

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_auto_20180123_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Location Tag',
                'verbose_name_plural': 'Location Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Subject Tag',
                'verbose_name_plural': 'Subject Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='place_tags',
            field=taggit.managers.TaggableManager(help_text='??. Select all that apply or create additional ones.', related_name='place_tags', through='asset.TaggedPlace', to='asset.LocationTag', verbose_name='Location keywords'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='subject_tags',
            field=taggit.managers.TaggableManager(help_text='??. Select all that apply or create additional ones.', related_name='subject_tags', through='asset.TaggedSubject', to='asset.SubjectTag', verbose_name='Description keywords'),
        ),
        migrations.AlterField(
            model_name='taggedplace',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_taggedplace_items', to='asset.LocationTag'),
        ),
        migrations.AlterField(
            model_name='taggedsubject',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_taggedsubject_items', to='asset.SubjectTag'),
        ),
    ]
