# Generated by Django 2.0 on 2018-02-13 18:35

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_auto_20180123_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypedTag',
        ),
        migrations.AlterField(
            model_name='asset',
            name='data_contact_state',
            field=models.CharField(choices=[('', 'State'), ('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('DC', 'DC'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('PR', 'PR'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('VI', 'VI'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(help_text='Enter a description which provides detailed information about the use, timing, location, and methods of data collection or analysis. (Max 10,000 characters)', max_length=10000, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='end_month',
            field=models.CharField(blank=True, choices=[('', 'Choose'), ('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3, null=True, verbose_name='Collection end month'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='isContracted',
            field=models.BooleanField(default=False, help_text='Check this for assets in which the storage or maintenance ofthe asset are performed through a contractual aggreeement with a non-fws entity.', verbose_name='Contracted'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='partners',
            field=models.CharField(blank=True, help_text='Include all partners as a comma separated list, that have direct involvement in the collection, storage, or maintenance of the asset.', max_length=100, null=True, verbose_name='Partners'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='place_tags',
            field=taggit.managers.TaggableManager(help_text='Select all that apply. Additional keywords can be created by typing the desired keyword, followed by selecting it from the menu or &lt;Enter&gt;.', related_name='place_tags', through='asset.TaggedPlace', to='asset.LocationTag', verbose_name='Location keywords'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='primary_contact_state',
            field=models.CharField(choices=[('', 'State'), ('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('DC', 'DC'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('PR', 'PR'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('VI', 'VI'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='spatial_scale',
            field=models.CharField(choices=[('', 'Choose Scale'), ('BCR', 'BCR'), ('multi-state/province', 'multi-state/province'), ('single state/province', 'single state/province'), ('local', 'local')], help_text='Choose the spatial scale that best represents the largest scale that the data are collected.', max_length=15),
        ),
        migrations.AlterField(
            model_name='asset',
            name='start_month',
            field=models.CharField(blank=True, choices=[('', 'Choose'), ('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3, null=True, verbose_name='Collection start month'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('', 'Choose status'), ('Operational', 'Operational'), ('Inactive', 'Inactive'), ('Experimental', 'Experimental')], help_text='Select the value that best represents the current status of the asset. `Inactive` should be used for assets that have ceased operations or have been discontinued.', max_length=23, verbose_name='Asset Status'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='subject_tags',
            field=taggit.managers.TaggableManager(help_text='Select all that apply. Additional keywords can be created by typing the desired keyword, followed by selecting it from the menu or &lt;Enter&gt;.', related_name='subject_tags', through='asset.TaggedSubject', to='asset.SubjectTag', verbose_name='Description keywords'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='data_contact_state',
            field=models.CharField(choices=[('', 'State'), ('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('DC', 'DC'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('PR', 'PR'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('VI', 'VI'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='description',
            field=models.TextField(help_text='Enter a description which provides detailed information about the use, timing, location, and methods of data collection or analysis. (Max 10,000 characters)', max_length=10000, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='end_month',
            field=models.CharField(blank=True, choices=[('', 'Choose'), ('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3, null=True, verbose_name='Collection end month'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='isContracted',
            field=models.BooleanField(default=False, help_text='Check this for assets in which the storage or maintenance ofthe asset are performed through a contractual aggreeement with a non-fws entity.', verbose_name='Contracted'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='partners',
            field=models.CharField(blank=True, help_text='Include all partners as a comma separated list, that have direct involvement in the collection, storage, or maintenance of the asset.', max_length=100, null=True, verbose_name='Partners'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='primary_contact_state',
            field=models.CharField(choices=[('', 'State'), ('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('DC', 'DC'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('PR', 'PR'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('VI', 'VI'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='spatial_scale',
            field=models.CharField(choices=[('', 'Choose Scale'), ('BCR', 'BCR'), ('multi-state/province', 'multi-state/province'), ('single state/province', 'single state/province'), ('local', 'local')], help_text='Choose the spatial scale that best represents the largest scale that the data are collected.', max_length=15),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='start_month',
            field=models.CharField(blank=True, choices=[('', 'Choose'), ('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3, null=True, verbose_name='Collection start month'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='status',
            field=models.CharField(choices=[('', 'Choose status'), ('Operational', 'Operational'), ('Inactive', 'Inactive'), ('Experimental', 'Experimental')], help_text='Select the value that best represents the current status of the asset. `Inactive` should be used for assets that have ceased operations or have been discontinued.', max_length=23, verbose_name='Asset Status'),
        ),
    ]
