# Generated by Django 2.0 on 2018-02-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_auto_20180213_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='spatial_scale',
            field=models.CharField(choices=[('', 'Choose Scale'), ('BCR', 'BCR'), ('multi-state/province', 'multi-state/province'), ('single state/province', 'single state/province'), ('local', 'local')], help_text='Choose the spatial scale that best represents the largest scale that the data are collected.', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='spatial_scale',
            field=models.CharField(choices=[('', 'Choose Scale'), ('BCR', 'BCR'), ('multi-state/province', 'multi-state/province'), ('single state/province', 'single state/province'), ('local', 'local')], help_text='Choose the spatial scale that best represents the largest scale that the data are collected.', max_length=25),
        ),
    ]
