# Generated by Django 2.0 on 2018-03-03 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_auto_20180213_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='If this data asset shares a common history, administration, decision context, and/or species + location + platform that requires coordinated planning and management, select the assest that is its parent.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_asset', to='asset.Asset', verbose_name='Parent Asset'),
        ),
    ]
