# Generated by Django 2.0 on 2018-03-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_auto_20180213_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(help_text='A descriptive name of the asset.', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('', 'Choose status'), ('Operational', 'Operational'), ('Inactive', 'Inactive'), ('Experimental', 'Experimental')], help_text='Select the value that best represents the current status of the asset. `Inactive` should be used for assets that have ceased operations or have been discontinued.', max_length=23, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='name',
            field=models.CharField(help_text='A descriptive name of the asset.', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='status',
            field=models.CharField(choices=[('', 'Choose status'), ('Operational', 'Operational'), ('Inactive', 'Inactive'), ('Experimental', 'Experimental')], help_text='Select the value that best represents the current status of the asset. `Inactive` should be used for assets that have ceased operations or have been discontinued.', max_length=23, verbose_name='Status'),
        ),
    ]
