# Generated by Django 2.0.3 on 2018-03-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_auto_20180303_0805'),
        ('asset', '0017_update_spatial_scale'),
    ]

    operations = [
    ]
