# Generated by Django 2.2.6 on 2019-11-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0019_auto_20191009_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='last_modified',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.Organization', verbose_name='Primary Organization of Stewardship'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If this data asset shares a common history, administration, decision context, and/or species + location + platform that requires coordinated planning and management, select the assest that is its parent.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.Asset', verbose_name='Parent Asset'),
        ),
    ]
