# Generated by Django 2.2.11 on 2020-03-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0020_auto_20191115_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='partners',
            field=models.CharField(blank=True, help_text='Include all partners as a comma separated list, that have direct involvement in the collection, storage, or maintenance of the asset.', max_length=5000, null=True, verbose_name='Partners'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='partners',
            field=models.CharField(blank=True, help_text='Include all partners as a comma separated list, that have direct involvement in the collection, storage, or maintenance of the asset.', max_length=5000, null=True, verbose_name='Partners'),
        ),
    ]
